// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lmsAPI.Data;

#nullable disable

namespace lmsAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220320081849_adminRoleRelation")]
    partial class adminRoleRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lmsAPI.admin", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("admin_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("passwordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.HasKey("email");

                    b.HasIndex("role_id");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("lmsAPI.job_titles", b =>
                {
                    b.Property<int>("jobtitle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("jobtitle_id"));

                    b.Property<string>("jobtitle_decription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("jobtitle_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("jobtitle_id");

                    b.ToTable("job_titles");
                });

            modelBuilder.Entity("lmsAPI.roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("role_description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role_platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("lmsAPI.admin", b =>
                {
                    b.HasOne("lmsAPI.roles", "role_")
                        .WithMany("admin")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role_");
                });

            modelBuilder.Entity("lmsAPI.roles", b =>
                {
                    b.Navigation("admin");
                });
#pragma warning restore 612, 618
        }
    }
}
